#################################################################################
# This is an example script that echos the vars generated by MegaMerge.
#################################################################################


echo $password
echo $watchmangroup
echo $namesync

